# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.



HEADERS += ./MyMainWindow.h
SOURCES += ./main.cpp \
    ./MyMainWindow.cpp
FORMS += ./MyMainWindow.ui
RESOURCES += MyMainWindow.qrc
